/**
 * Placement test questions — 4 per world, progressively harder.
 * Score determines starting chapter (1, 2 or 3).
 * Each question is tagged with difficulty: 1=beginner, 2=intermediate, 3=advanced
 */

export type PlacementQ = {
  id: string;
  world: "fundamentals" | "dj" | "producer";
  difficulty: 1 | 2 | 3;
  q: string;
  options: string[];
  answer: number;
  explain: string;
};

export const PLACEMENT_QUESTIONS: PlacementQ[] = [

  // ── FUNDAMENTALS ──────────────────────────────────────────────────────────
  {
    id: "f1", world: "fundamentals", difficulty: 1,
    q: "What does frequency determine in a sound wave?",
    options: ["Volume", "Pitch", "Timbre", "Reverb"],
    answer: 1,
    explain: "Frequency is the number of cycles per second (Hz) — the higher the frequency, the higher the pitch.",
  },
  {
    id: "f2", world: "fundamentals", difficulty: 1,
    q: "A 4/4 time signature means…",
    options: ["4 beats per bar, quarter note gets the beat", "4 bars per minute", "4 instruments in the mix", "4 quarter notes per second"],
    answer: 0,
    explain: "The top number = beats per bar. The bottom number = which note value gets one beat. 4/4 = 4 quarter notes per bar.",
  },
  {
    id: "f3", world: "fundamentals", difficulty: 2,
    q: "Which scale pattern is: W W H W W W H?",
    options: ["Natural minor", "Pentatonic", "Major", "Dorian"],
    answer: 2,
    explain: "The major scale follows the pattern Whole-Whole-Half-Whole-Whole-Whole-Half steps. It's the most fundamental scale in Western music.",
  },
  {
    id: "f4", world: "fundamentals", difficulty: 3,
    q: "A chord with the root, major 3rd and augmented 5th is called…",
    options: ["Diminished", "Major", "Augmented", "Suspended"],
    answer: 2,
    explain: "An augmented triad raises the 5th by a semitone (e.g. C-E-G#). It creates a tense, unresolved sound often used in jazz and film music.",
  },

  // ── DJ WORLD ──────────────────────────────────────────────────────────────
  {
    id: "d1", world: "dj", difficulty: 1,
    q: "What does BPM stand for?",
    options: ["Bass Per Mix", "Beats Per Minute", "Beat Pattern Marker", "Bass Pattern Mode"],
    answer: 1,
    explain: "BPM = Beats Per Minute. It measures the tempo of a track. House music typically runs 120-130 BPM.",
  },
  {
    id: "d2", world: "dj", difficulty: 1,
    q: "In rekordbox, what does a HOT CUE do?",
    options: ["Adjusts the EQ", "Marks and instantly jumps to a point in a track", "Changes the BPM", "Loops the last 4 bars"],
    answer: 1,
    explain: "Hot cues let you mark key moments (drops, build-ups) and jump to them instantly during a live set with a single button press.",
  },
  {
    id: "d3", world: "dj", difficulty: 2,
    q: "The Camelot Wheel is used for…",
    options: ["Measuring BPM accurately", "Harmonic mixing — matching keys between tracks", "Building playlists by genre", "Setting headphone volume"],
    answer: 1,
    explain: "The Camelot Wheel maps musical keys to numbers (1-12) and letters (A/B). Adjacent keys mix harmonically — no clashing notes.",
  },
  {
    id: "d4", world: "dj", difficulty: 3,
    q: "During a long blend, which EQ technique prevents bass clash between two tracks?",
    options: ["Cut highs on both tracks", "Bass swap — cut bass on incoming track, fade out bass on outgoing", "Boost mids on both", "Use reverb on the crossfader"],
    answer: 1,
    explain: "The three-band EQ bass swap: cut the incoming track's bass to 0 while it fades in, then swap — bring the new bass up as the old one cuts. Prevents two kick drums fighting.",
  },

  // ── PRODUCER ──────────────────────────────────────────────────────────────
  {
    id: "p1", world: "producer", difficulty: 1,
    q: "In Ableton Live, what is the difference between Session View and Arrangement View?",
    options: [
      "Session View is for MIDI, Arrangement View is for audio",
      "Session View is a clip launcher for jamming; Arrangement View is a timeline for composing",
      "Session View records audio; Arrangement View edits MIDI",
      "They are the same view with different colour schemes",
    ],
    answer: 1,
    explain: "Session View = vertical grid of clips for live looping and jamming. Arrangement View = horizontal timeline for composing finished tracks.",
  },
  {
    id: "p2", world: "producer", difficulty: 1,
    q: "What does MIDI data contain?",
    options: ["Actual audio waveforms", "Instructions (notes, velocity, timing) that trigger sounds", "Compressed MP3 audio", "Plug-in settings only"],
    answer: 1,
    explain: "MIDI is not audio — it's data: which note, how hard, when. The actual sound is generated by whichever instrument plugin receives the MIDI.",
  },
  {
    id: "p3", world: "producer", difficulty: 2,
    q: "What does a compressor do to audio dynamics?",
    options: [
      "Makes the signal louder at all times",
      "Reduces the volume of loud parts, making the overall level more consistent",
      "Adds harmonic distortion to the signal",
      "Filters out high frequencies",
    ],
    answer: 1,
    explain: "A compressor attenuates signals above a threshold. This evens out the dynamic range — loud peaks are controlled, so you can turn the whole thing up.",
  },
  {
    id: "p4", world: "producer", difficulty: 3,
    q: "In sidechain compression, the compressor's gain reduction is triggered by…",
    options: [
      "The signal on the same track",
      "An external signal (e.g. the kick drum) fed into the sidechain input",
      "The master bus level",
      "A low-frequency oscillator",
    ],
    answer: 1,
    explain: "Sidechain compression uses a separate 'key' signal (usually kick drum) to trigger the compressor on another track (usually bass). This creates the classic 'pumping' effect.",
  },
];

/**
 * Given correct answers per world, return the chapter to unlock (1-3).
 * 0 correct = chapter 1 (start from scratch)
 * 1 correct = chapter 1
 * 2 correct = chapter 2 (skip intro)
 * 3-4 correct = chapter 3 (skip ahead significantly)
 */
export function scorePlacement(
  answers: Record<string, boolean>,
  world: "fundamentals" | "dj" | "producer",
): number {
  const worldQs = PLACEMENT_QUESTIONS.filter(q => q.world === world);
  const correct = worldQs.filter(q => answers[q.id]).length;
  if (correct >= 3) return 3;
  if (correct >= 2) return 2;
  return 1;
}
